post http://localhost:2000/createusers
Content-Type: application/json

{
    "name":"superadmin",
    "username":"superadmin",
    "password":"superadmin",
    "role":"superadmin"
}

###
post http://localhost:2000/createusers
Content-Type: application/json

{
    "name":"testsiswa5",
    "username":"testsiswa5",
    "password":"testsiswa5",
    "role":"siswa",
    "jurusanId":2
}

###
put http://localhost:2000/updateusers/7
Content-Type: application/json

{
    "name":"testadmin",
    "username":"testadmin",
    "password":"testadmin",
    "role":"admin",
    "jurusanId":2
}

###
delete http://localhost:2000/deleteusers/9

###
get http://localhost:2000/getusers

###
get http://localhost:2000/getjurusan

###
delete http://localhost:2000/deletejurusan/3


###
post http://localhost:2000/createjurusan
Content-Type: application/json

{
    "namaJurusan":"X PM1"
}

###
post http://localhost:2000/login
Content-Type: application/json

{
    "username": "testadmin",
    "password": "testadmin"
}

###
get http://localhost:2000/me

###
delete http://localhost:2000/logout

###
get http://localhost:2000/getabsenhariini

###
get http://localhost:2000/getabsensi

###
put http://localhost:2000/updateabsensi/4
Content-Type: application/json

{
 "jam_masuk": "07:00",
  "jam_keluar": "18:00"
}

###
delete http://localhost:2000/deletelaporan/1